### PR TITLE
Sub-header component created with assets and provisional description

### PR DESCRIPTION
**Pull request by Nzone56**
I promise I'll take pull requests seriously
I promise I'll take pull requests seriously
I promise I'll take pull requests seriously
I promise I'll take pull requests seriously
I promise I'll take pull requests seriously
I promise I'll take pull requests seriously
I promise I'll take pull requests seriously
I promise I'll take pull requests seriously
I promise I'll take pull requests seriously
I promise I'll take pull requests seriously
... or not

### CODE REVIEW

**Review by ncondes — CHANGES_REQUESTED** [review]
SoundCloud? Is this a joke? Please fix the introduction paragraph

Screenshot 2023-04-14 at 9 28 59 AM

Right now the icons overlaps the text, fix this.

I don't want static assets in the src directory, please move the .png files to the public directory

path: public/assets/img

inside this folder move the .png files named as follow:

background: introduction-background.png
icons: introduction-icons.png

remember to use semantic HTML, change the wrapper div element of the Introduction component to a section tag

**Comment by Nzone56** [comment]
I forgot to change the name when i ask chatgpt for the description jsdjds mb 
The overlapping was due small windows, but i fixed that and shouldnt be one over another till around 800px 
Move the images to the new directory and change the div for section

**Comment by Nzone56** [comment]
Also i managed to put the little extra section in the background img that appeared in the mockup.

**Review by ncondes — APPROVED** [review]
image

**Pull request merged**
