### PR TITLE
SS012/SS013/SS014/SS015

### PR DESCRIPTION
**Pull request by Nzone56**
* SS012: Read, understand and implement react-hook-form
* SS013 Create all login form validations and tested it 
* SS014 Create all register form validations and tested it 
* SS015 In the process of SS013 and SS014 I ended up doing this one too, but without creating a reusable component, I await feedback on how I should fix/improve this task, leave it in "doing" until I wait for the response of this pull request

### CODE REVIEW

**Review by ncondes — APPROVED** [review]
Awesome Job!

image

**Comment by ncondes** [comment]
I'll hold off this pull request until you complete the reusable component. hint: take a look at the HOC pattern.

**Comment by Nzone56** [comment]
I have doned the SS016 without HOC,  it was kinda rough trying to do that way and i ended up making such a mess with libraries and the yupi for creating the schem onlyt ofr the rules so i turn that down and ended up making it way more simplier, if u want me to do that with the HOC pattern like 100% needed just let me know in the comments and i ll resign for sure !  xd

**Review by ncondes — CHANGES_REQUESTED** [review]
https://react-hook-form.com/api/usecontroller/controller

Take a look at this Component provided by the react hook form team.

**Comment by Nzone56** [comment]
I saw the controller component documentation from react-hook-from that u provided but i wasnt really sure what u really wanted so i ended up replacing the register from the same library and using that component on the reuable one InputField, and ofc the implementation of this in the Register and Login components, let me know if thats what u wanted me to do or i just messsed up the code with some random lines jdsjsd

**Comment by ncondes** [comment]
Yes, please use the Controller component, see that it takes a prop named 'render' and the value for this prop is a function that return JSX (another component) this is known as a HOC (High Order Component) this is a very common pattern for react development.

**Comment by Nzone56** [comment]
So.... the code its fine, right? xd

**Review by ncondes — APPROVED** [review]

**Pull request merged**
